version: "3.9"

services:
  api:
    depends_on:
      - db-test
    env_file:
      - .env.test
    ports:
      - "8009:8080"
    volumes:
      - ./:/home/app/:delegated

  db-test:
    image: "postgres:13.3-alpine"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=thisissparta
      - POSTGRES_DB=api
